name: Build Web App
on: [push]
jobs:
  build:
    runs-on: windows-latest
    env:
      newVersion: 0.0.0.0
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.0.2
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
     
    - name: Restore NuGet Packages
      run: nuget restore DungeonPapperWPF.sln
    - name: Patch version number 
      shell: powershell
      run: |
       $4= $env:GITHUB_RUN_NUMBER
        (Get-Content -Path .\Properties\AssemblyInfo.cs) -replace '\"([0-9]+)\.([0-9]+)\.([0-9]+)\.([0-9]+)\"' , """`$1.`$2.`$3.$4""" `
        | Set-Content -Path .\Properties\AssemblyInfo.cs
    - name: Set New Version to Environment
      shell: powershell
      run: |
        $newVersion=(Select-String -Path .\Properties\AssemblyInfo.cs -Pattern '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' | select -first 1).Matches.Value
        $newVersion
        # Setting env variable to make available in next step is wired https://www.jamescroft.co.uk/setting-github-actions-environment-variables-in-powershell/.
        echo "newVersion=$newVersion" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
    - name: Build and Publish Web App
      run: msbuild DungeonPapperWPF.sln /p:Configuration=Release
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Release Binaries
        path: ./bin/Release
    - name: Install 7Zip PowerShell Module
      shell: powershell
      run: Install-Module 7Zip4PowerShell -Force -Verbose
    - name: Zip the artifacts
      shell: powershell
      run: Compress-7Zip "DungeonPapperWPF/bin/Release" -ArchiveFileName "DungeonPapperWPF_$($env:newVersion).zip" -Format Zip
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.newVersion }}
        release_name: v${{ env.newVersion }}
        body: |
            Automated Release by GitHub Action CI
        draft: false
        prerelease: true
    - name: Upload Assets to Release
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./DungeonPapperWPF_${{env.newVersion}}.zip
        asset_name: DungeonPapperWPF_${{env.newVersion}}.zip
        asset_content_type: application/zip
